name: Deploy Docker images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '42 8 * * *'

jobs:

  publish:
    name: Deploy images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build images
        run: make

      - name: Test images
        run: make test

      - name: Push base image
        run: docker push nyholm/roave-bc-check:base

      - name: Push imags
        run: |
            docker push nyholm/roave-bc-check:latest
            docker push nyholm/roave-bc-check:stable
            docker push nyholm/roave-bc-check:8.x

      - name: Build gh-action image
        run: docker build -t nyholm/roave-bc-check-ga:latest gh-action

      - name: Push gh-action image
        run: docker push nyholm/roave-bc-check-ga:latest
